############# Portuguese navigation ##############

# main menu
[[main]]
name = "Início"
url = ""
weight = 1

[[main]]
name = "Sobre"
url = "about/"
weight = 2

[[main]]
name = "Projeto"
url = "project/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "Mais"
hasChildren = true

  [[main]]
  parent = "Mais"
  name = "Serviço"
  url = "service/"
  weight = 1

  [[main]]
  parent = "Mais"
  name = "Preços"
  url = "pricing/"
  weight = 2

  [[main]]
  parent = "Mais"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Contacto"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Sobre"
url = "about/"
weight = 2

[[footer]]
name = "Projeto"
url = "project/"
weight = 3

[[footer]]
name = "Serviço"
url = "service/"
weight = 4

[[footer]]
name = "Preços"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contacto"
url = "contact/"
weight = 7